name: ember-cli-code-coverage

on: [pull_request]

jobs:
  build:
    name: Code Coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: yarn install
    - uses: mydea/ember-cli-code-coverage-action@v1
      with:
        repo-token: "${{ secrets.CONDUIT_PAT }}"
